import Head from "next/head";
import Hero from "../Componentes/Hero";
import Layout from "../Componentes/Layout";
import css from '../styles/Home.module.css'

export default function Home() {
  return (
      <Layout>
        <div className={css.container}>
          <Head>
            <title>Proyecto</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/Logo.png" />
          </Head>
          {/* body */}
          <main>
            <Hero/>       
          </main>
        </div>
      </Layout>
  );
}

