import Head from "next/head";
import Hero from "../Componentes/Hero";
import Layout from "../Componentes/Layout";
import Services from "../Componentes/Services";
import css from '../styles/Home.module.css'

export default function Home() {
  return (
      <Layout>
        <div className={css.container}>
          <Head>
            <title>Proyecto</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/Logo.png" />
            <link href="https://fonts.googleapis.com/css2?family=Crafty+Girls&display=swap" rel="stylesheet"/>
          </Head>
          {/* body */}
          <main>
            <Hero/> 
            <Services/>      
          </main>
        </div>
      </Layout>
  );
}

